# Generated by Django 4.2.4 on 2023-08-17 04:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clientname', models.CharField(max_length=255, verbose_name='Client Name')),
                ('Clientimage', models.ImageField(blank=True, null=True, upload_to='client_images/', verbose_name='Client Image')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Email', models.EmailField(max_length=255, verbose_name='Email')),
                ('Message', ckeditor.fields.RichTextField(verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projectname', models.CharField(max_length=255, verbose_name='Project Name')),
                ('Projectdescription', ckeditor.fields.RichTextField(verbose_name='Project Description')),
                ('Projectlink', models.URLField(max_length=500, verbose_name='Project Link')),
                ('Projectimage', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Project Image')),
                ('Projectcasestudy', ckeditor.fields.RichTextField(blank=True, verbose_name='Project Case Study')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serviceicon', models.CharField(max_length=50, verbose_name='Service Icon')),
                ('Servicename', models.CharField(max_length=255, verbose_name='Service Name')),
                ('Servicedescription', ckeditor.fields.RichTextField(verbose_name='Service Description')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=255, verbose_name='Team Name')),
                ('Teamimage', models.ImageField(blank=True, null=True, upload_to='team_images/', verbose_name='Team Image')),
                ('Teamdesignation', models.CharField(max_length=255, verbose_name='Team Designation')),
                ('Teamtwitter', models.CharField(blank=True, max_length=255, verbose_name='Team Twitter')),
                ('Teamfacebook', models.CharField(blank=True, max_length=255, verbose_name='Team Facebook')),
                ('Teaminstagram', models.CharField(blank=True, max_length=255, verbose_name='Team Instagram')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonialname', models.CharField(max_length=255, verbose_name='Testimonial Name')),
                ('Testimonialimage', models.ImageField(blank=True, null=True, upload_to='testimonial_images/', verbose_name='Testimonial Image')),
                ('Testimonialtext', ckeditor.fields.RichTextField(verbose_name='Testimonial Text')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
